In [150]:
#Importacion de las librerias, ademas de la base de dtos sucia import pandas as pd
import pandas as pd
import numpy as np
df=pd.read_csv("C:/Users/ricru/Documents/df_sucio.csv")
df

,Amount,Severity,Age,Private Attorney,Marital Status,Specialty,Insurance,Gender
0,57041.0,7.0,62.0,1,NaN,Family Practice,Private,Male
1,324976.0,6.0,38.0,1,2.0,NaN,No Insurance,Female
2,135383.0,4.0,34.0,1,2.0,Cardiology,Unknown,Male
3,829742.0,7.0,42.0,1,1.0,Pediatrics,No Insurance,Female
4,197675.0,3.0,60.0,0,2.0,OBGYN,Medicare/Medicaid,Female
...,...,...,...,...,...,...,...,...
94589,146059.0,3.0,56.0,0,2.0,OBGYN,Unknown,Female
94590,908341.0,8.0,35.0,1,2.0,Orthopedic Surgery,Unknown,Male
94591,39355.0,3.0,42.0,0,4.0,Emergency Medicine,Medicare/Medicaid,Male
94592,827167.0,6.0,57.0,1,0.0,Dermatology,Private,Male
94593,134090.0,9.0,63.0,1,4.0,Neurology/Neurosurgery,Medicare/Medicaid,Female

## Acerca del Data Set 
El conjunto de datos proporcionado es un archivo CSV que contiene información tabular con múltiples columnas y filas.
Cada Columna representa una variable diferente, y cada Fila representa un registro diferente. Algunas columnas pueden contener datos numéricos, mientras que otras pueden contener datos categóricos o de texto. El objetivo es limpiar y preparar estos datos para su análisis posterior.


**Amount:** Representa una cantidad monetaria del reclamo de los familiares en dolares


**Severity:** Es la calificación de gravedad del daño al paciente, de 1 (trauma emocional) a 9 (muerte)

**Nivel,Descripción**


    9: Muerte


    8: Daño permanente grave


    7: Daño permanente


    6: Daño temporal


    5: Tratamiento adicional


    4: Angustia o incomodidad emocional


    3:"No hay daño evidente, físico o de otro tipo."


    2: No llegó al paciente

    
    1: Condición insegura


**Age:** Edad del reclamante en años


**Private Attorney:** En caso de que el reclamante haya sido representado por algun abogado privado

    0: No ha sido representado
    1: Fue representado

**Marital status:** Estado civil del reclamante


Estado civil: 0 (Divorciado), 1 (Soltero), 2 (Casado), 3 (Viudo), 4 (Desconocido)

**Speciality:** Especialidad del medico involucrado en la demanda


**Insurance:** Tipo de Seguro medico con el que contaba el paciente

**Medicare** es principalmente para personas mayores de 65 años y para personas con ciertas discapacidades, independientemente de sus ingresos. **Medicaid**es un programa estatal y federal que proporciona cobertura médica a personas de bajos ingresos, familias y niños, mujeres embarazadas y personas con discapacidades


**Género:** Género del Paciente afectado

In [151]:
#Visualizacion del total de las filas y de las columnas 
df.shape

(94594, 8)

In [152]:
#Mostrar el tipo de datos de cada columna, como categoricas y numericas
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94594 entries, 0 to 94593
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Amount            91757 non-null  float64
 1   Severity          91757 non-null  float64
 2   Age               91757 non-null  float64
 3   Private Attorney  91757 non-null  object
 4   Marital Status    89918 non-null  float64
 5   Specialty         91757 non-null  object
 6   Insurance         91757 non-null  object
 7   Gender            91757 non-null  object
dtypes: float64(4), object(4)
memory usage: 5.8+ MB

In [185]:
df.describe()

              Amount      Severity           Age  Marital Status
count   91757.000000  91757.000000  91757.000000    89918.000000
mean   157400.956047      4.796332     42.650599        1.891412
std    193150.425005      2.081919     19.811324        1.003014
min      1576.000000      1.000000      0.000000        0.000000
25%     43697.000000      3.000000     28.000000        1.000000
50%     97829.000000      4.000000     43.000000        2.000000
75%    154517.000000      7.000000     58.000000        2.000000
max    926411.000000      9.000000     87.000000        4.000000

## Informacion sobre las columnas

In [153]:
lista= df.columns
lista

Index(['Amount', 'Severity', 'Age', 'Private Attorney', 'Marital Status',
       'Specialty', 'Insurance', 'Gender'],
      dtype='object')

In [154]:
import pandas as pd

# Asumimos que tu DataFrame se llama df1

print("--- Análisis de Valores Únicos por Columna ---")
print(f"Número total de filas: {len(df)}\n")

for columna in df.columns:
    
    num_valores_unicos = df[columna].nunique()

    
    print(f" Columna: '{columna}'")
    print(f"   - Cantidad de Valores Únicos: {num_valores_unicos}")
    
    if num_valores_unicos < 50:
        valores_unicos = df[columna].unique()
        print(f"   - Valores Únicos: {valores_unicos}")
    else:
        print("   - (Contiene demasiados valores únicos. Se omite la impresión).")

--- Análisis de Valores Únicos por Columna ---
Número total de filas: 94594

 Columna: 'Amount'
   - Cantidad de Valores Únicos: 66269
   - (Contiene demasiados valores únicos. Se omite la impresión).
 Columna: 'Severity'
   - Cantidad de Valores Únicos: 9
   - Valores Únicos: [ 7.  6.  4.  3.  9. nan  1.  5.  2.  8.]
 Columna: 'Age'
   - Cantidad de Valores Únicos: 88
   - (Contiene demasiados valores únicos. Se omite la impresión).
 Columna: 'Private Attorney'
   - Cantidad de Valores Únicos: 3
   - Valores Únicos: ['1' '0' nan 'Auto%#']
 Columna: 'Marital Status'
   - Cantidad de Valores Únicos: 5
   - Valores Únicos: [nan  2.  1.  4.  0.  3.]
 Columna: 'Specialty'
   - Cantidad de Valores Únicos: 21
   - Valores Únicos: ['Family Practice' nan 'Cardiology' 'Pediatrics' 'OBGYN'
 'Internal Medicine' 'Anesthesiology' 'Emergency Medicine' 'Ophthamology'
 'Urological Surgery' 'Orthopedic Surgery' 'Neurology/Neurosurgery'
 'Occupational Medicine' 'Resident' 'Thoracic Surgery' 'General Surgery'
 'Radiology' 'Pathology' 'Physical Medicine' 'Plastic Surgeon' 'Auto%#'
 'Dermatology']
 Columna: 'Insurance'
   - Cantidad de Valores Únicos: 5
   - Valores Únicos: ['Private' 'No Insurance' 'Unknown' 'Medicare/Medicaid' nan
 'Workers Compensation']
 Columna: 'Gender'
   - Cantidad de Valores Únicos: 3
   - Valores Únicos: ['Male' 'Female' 'Auto%#' nan]

In [155]:
# Información sobre valores nulos en cada columna   
df.isnull().sum()

Amount              2837
Severity            2837
Age                 2837
Private Attorney    2837
Marital Status      4676
Specialty           2837
Insurance           2837
Gender              2837
dtype: int64

In [156]:
#Se mostrara un true en caso de que exista algun valor nulo en el dataframe o un False en caso de que si contenga un valor valido.
df.isnull()

,Amount,Severity,Age,Private Attorney,Marital Status,Specialty,Insurance,Gender
0,False,False,False,False,True,False,False,False
1,False,False,False,False,False,True,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
94589,False,False,False,False,False,False,False,False
94590,False,False,False,False,False,False,False,False
94591,False,False,False,False,False,False,False,False
94592,False,False,False,False,False,False,False,False
94593,False,False,False,False,False,False,False,False

In [157]:
#saber cuantas filas duplicadas hay en el dataframe, sin embargo se pueden repetir ya que no son valores como un ID
df.duplicated().sum()

np.int64(8463)

## Limpieza de datos

In [158]:
df1=df.copy()

In [159]:
df2=df1.copy()

In [160]:

traduccions= {
    'Family Practice': 'Medicina Familiar', 
    'Cardiology': 'Cardiologia',
    'Pediatrics' : 'Pediatria',
    'OBGYN' : 'Ginecologia y Obstetricia',
    'Internal Medicine': 'Medicina Interna',
    'Anesthesiology' : 'Anestesiologia',
    'Emergency Medicine': 'Medicina de Emergencia',
    'Ophthamology' : 'Oftalmologia',
    'Urological Surgery': 'Cirugia Urologica',
    'Orthopedic Surgery' : 'Cirugia Ortopedica',
    'Neurology/Neurosurgery': 'Neurologia/Neurocirugia',
    'Occupational Medicine' : 'Medicina Ocupacional',
    'Resident' : 'Residente',
    'Thoracic Surgery' : 'Cirugia Toracica',
    'General Surgery' : 'Cirugia General',
    'Radiology' : 'Radiologia',
    'Pathology' : 'Patologia',
    'Physical Medicine' : 'Medicina Fisica',
    'Plastic Surgeon'  : 'Cirujano Plastico'
     
}
traduccioni= {
    'Private': 'Privado',
    'No Insurance': 'Sin Seguro',
    'Medicare/Medicaid' : 'Medicare/Medicaid',
    'Workers Compensation' : 'Compensacion de Trabajadores',
    'Unknown': 'Desconocido',
    'Other' : 'Otro'
    
}
traducciong= {
    'Female': 'Femenino',
    'Male': 'Masculino'
}

In [161]:
df['Insurance'].unique()

array(['Private', 'No Insurance', 'Unknown', 'Medicare/Medicaid', nan,
       'Workers Compensation'], dtype=object)

In [162]:
df2 = df1.rename(columns={"Amount":"Monto","Severity":"Gravedad",	"Age":"Edad", "Private Attorney":"Abogado Privado", "Marital Status":"Estado Civil", "Specialty":"Especialidad", "Insurance":"Seguro","Gender":"Género"})
df2

,Monto,Gravedad,Edad,Abogado Privado,Estado Civil,Especialidad,Seguro,Género
0,57041.0,7.0,62.0,1,NaN,Family Practice,Private,Male
1,324976.0,6.0,38.0,1,2.0,NaN,No Insurance,Female
2,135383.0,4.0,34.0,1,2.0,Cardiology,Unknown,Male
3,829742.0,7.0,42.0,1,1.0,Pediatrics,No Insurance,Female
4,197675.0,3.0,60.0,0,2.0,OBGYN,Medicare/Medicaid,Female
...,...,...,...,...,...,...,...,...
94589,146059.0,3.0,56.0,0,2.0,OBGYN,Unknown,Female
94590,908341.0,8.0,35.0,1,2.0,Orthopedic Surgery,Unknown,Male
94591,39355.0,3.0,42.0,0,4.0,Emergency Medicine,Medicare/Medicaid,Male
94592,827167.0,6.0,57.0,1,0.0,Dermatology,Private,Male
94593,134090.0,9.0,63.0,1,4.0,Neurology/Neurosurgery,Medicare/Medicaid,Female

In [163]:
df2['Género'] = df2['Género'].replace(traducciong)
df2['Seguro'] = df2['Seguro'].replace(traduccioni)
df2['Especialidad'] = df2['Especialidad'].replace(traduccions)
df2

,Monto,Gravedad,Edad,Abogado Privado,Estado Civil,Especialidad,Seguro,Género
0,57041.0,7.0,62.0,1,NaN,Medicina Familiar,Privado,Masculino
1,324976.0,6.0,38.0,1,2.0,NaN,Sin Seguro,Femenino
2,135383.0,4.0,34.0,1,2.0,Cardiologia,Desconocido,Masculino
3,829742.0,7.0,42.0,1,1.0,Pediatria,Sin Seguro,Femenino
4,197675.0,3.0,60.0,0,2.0,Ginecologia y Obstetricia,Medicare/Medicaid,Femenino
...,...,...,...,...,...,...,...,...
94589,146059.0,3.0,56.0,0,2.0,Ginecologia y Obstetricia,Desconocido,Femenino
94590,908341.0,8.0,35.0,1,2.0,Cirugia Ortopedica,Desconocido,Masculino
94591,39355.0,3.0,42.0,0,4.0,Medicina de Emergencia,Medicare/Medicaid,Masculino
94592,827167.0,6.0,57.0,1,0.0,Dermatology,Privado,Masculino
94593,134090.0,9.0,63.0,1,4.0,Neurologia/Neurocirugia,Medicare/Medicaid,Femenino

In [164]:
lista_col=df2.columns
lista_col

Index(['Monto', 'Gravedad', 'Edad', 'Abogado Privado', 'Estado Civil',
       'Especialidad', 'Seguro', 'Género'],
      dtype='object')

In [165]:
df2=df2.copy()

In [166]:
df2=df2.copy()
lista_col=df2.columns
for i in lista_col:
    df2=df2[df2[i] != 'invalid_value']
df2

,Monto,Gravedad,Edad,Abogado Privado,Estado Civil,Especialidad,Seguro,Género
0,57041.0,7.0,62.0,1,NaN,Medicina Familiar,Privado,Masculino
1,324976.0,6.0,38.0,1,2.0,NaN,Sin Seguro,Femenino
2,135383.0,4.0,34.0,1,2.0,Cardiologia,Desconocido,Masculino
3,829742.0,7.0,42.0,1,1.0,Pediatria,Sin Seguro,Femenino
4,197675.0,3.0,60.0,0,2.0,Ginecologia y Obstetricia,Medicare/Medicaid,Femenino
...,...,...,...,...,...,...,...,...
94589,146059.0,3.0,56.0,0,2.0,Ginecologia y Obstetricia,Desconocido,Femenino
94590,908341.0,8.0,35.0,1,2.0,Cirugia Ortopedica,Desconocido,Masculino
94591,39355.0,3.0,42.0,0,4.0,Medicina de Emergencia,Medicare/Medicaid,Masculino
94592,827167.0,6.0,57.0,1,0.0,Dermatology,Privado,Masculino
94593,134090.0,9.0,63.0,1,4.0,Neurologia/Neurocirugia,Medicare/Medicaid,Femenino

In [167]:
for i in lista_col:
    print(f"En la columna {i} los invalid_value son: {df2[df2[i] == 'invalid_value'].shape[0]}")

En la columna Monto los invalid_value son: 0
En la columna Gravedad los invalid_value son: 0
En la columna Edad los invalid_value son: 0
En la columna Abogado Privado los invalid_value son: 0
En la columna Estado Civil los invalid_value son: 0
En la columna Especialidad los invalid_value son: 0
En la columna Seguro los invalid_value son: 0
En la columna Género los invalid_value son: 0

In [168]:
#Estamos convirtiendo la columna 'Amount' a tipo numérico, forzando los valores no convertibles a NaN
df2['Monto'] = pd.to_numeric(df2['Monto'], errors='coerce')
df2

,Monto,Gravedad,Edad,Abogado Privado,Estado Civil,Especialidad,Seguro,Género
0,57041.0,7.0,62.0,1,NaN,Medicina Familiar,Privado,Masculino
1,324976.0,6.0,38.0,1,2.0,NaN,Sin Seguro,Femenino
2,135383.0,4.0,34.0,1,2.0,Cardiologia,Desconocido,Masculino
3,829742.0,7.0,42.0,1,1.0,Pediatria,Sin Seguro,Femenino
4,197675.0,3.0,60.0,0,2.0,Ginecologia y Obstetricia,Medicare/Medicaid,Femenino
...,...,...,...,...,...,...,...,...
94589,146059.0,3.0,56.0,0,2.0,Ginecologia y Obstetricia,Desconocido,Femenino
94590,908341.0,8.0,35.0,1,2.0,Cirugia Ortopedica,Desconocido,Masculino
94591,39355.0,3.0,42.0,0,4.0,Medicina de Emergencia,Medicare/Medicaid,Masculino
94592,827167.0,6.0,57.0,1,0.0,Dermatology,Privado,Masculino
94593,134090.0,9.0,63.0,1,4.0,Neurologia/Neurocirugia,Medicare/Medicaid,Femenino

In [169]:
df1.isnull().sum()

Amount              2837
Severity            2837
Age                 2837
Private Attorney    2837
Marital Status      4676
Specialty           2837
Insurance           2837
Gender              2837
dtype: int64

In [170]:
nan_indices = df2['Monto'].isna()
num_nan = nan_indices.sum()
random_numbers = np.random.randint(low=5000, high=20000, size=num_nan)
df2.loc[nan_indices, 'Monto'] = random_numbers
df2

,Monto,Gravedad,Edad,Abogado Privado,Estado Civil,Especialidad,Seguro,Género
0,57041.0,7.0,62.0,1,NaN,Medicina Familiar,Privado,Masculino
1,324976.0,6.0,38.0,1,2.0,NaN,Sin Seguro,Femenino
2,135383.0,4.0,34.0,1,2.0,Cardiologia,Desconocido,Masculino
3,829742.0,7.0,42.0,1,1.0,Pediatria,Sin Seguro,Femenino
4,197675.0,3.0,60.0,0,2.0,Ginecologia y Obstetricia,Medicare/Medicaid,Femenino
...,...,...,...,...,...,...,...,...
94589,146059.0,3.0,56.0,0,2.0,Ginecologia y Obstetricia,Desconocido,Femenino
94590,908341.0,8.0,35.0,1,2.0,Cirugia Ortopedica,Desconocido,Masculino
94591,39355.0,3.0,42.0,0,4.0,Medicina de Emergencia,Medicare/Medicaid,Masculino
94592,827167.0,6.0,57.0,1,0.0,Dermatology,Privado,Masculino
94593,134090.0,9.0,63.0,1,4.0,Neurologia/Neurocirugia,Medicare/Medicaid,Femenino

In [171]:
columna = 'Gravedad'
indices_nulos = df2[columna].isnull()
num_nulos = indices_nulos.sum()
valores_aleatorios = np.random.randint(1, 10, size=num_nulos).astype(float)
df2.loc[indices_nulos, columna] = valores_aleatorios

In [172]:
columna= "Edad"
indices_nulos = df2[columna].isnull()

num_nulos = indices_nulos.sum()
valores_aleatorios = np.random.randint(25, 75, size=num_nulos).astype(float)

df2.loc[indices_nulos, columna] = valores_aleatorios

In [173]:
columna = 'Abogado Privado'
indices_nulos = df2[columna].isnull()
num_nulos = indices_nulos.sum()
valores_aleatorios = np.random.randint(0, 2, size=num_nulos).astype(float)

df2.loc[indices_nulos, columna] = valores_aleatorios

In [174]:
columna = 'Estado Civil'

indices_nulos = df2[columna].isnull()
num_nulos = indices_nulos.sum()
valores_aleatorios = np.random.randint(0, 5, size=num_nulos).astype(float)

df2.loc[indices_nulos, columna] = valores_aleatorios
df2

,Monto,Gravedad,Edad,Abogado Privado,Estado Civil,Especialidad,Seguro,Género
0,57041.0,7.0,62.0,1,4.0,Medicina Familiar,Privado,Masculino
1,324976.0,6.0,38.0,1,2.0,NaN,Sin Seguro,Femenino
2,135383.0,4.0,34.0,1,2.0,Cardiologia,Desconocido,Masculino
3,829742.0,7.0,42.0,1,1.0,Pediatria,Sin Seguro,Femenino
4,197675.0,3.0,60.0,0,2.0,Ginecologia y Obstetricia,Medicare/Medicaid,Femenino
...,...,...,...,...,...,...,...,...
94589,146059.0,3.0,56.0,0,2.0,Ginecologia y Obstetricia,Desconocido,Femenino
94590,908341.0,8.0,35.0,1,2.0,Cirugia Ortopedica,Desconocido,Masculino
94591,39355.0,3.0,42.0,0,4.0,Medicina de Emergencia,Medicare/Medicaid,Masculino
94592,827167.0,6.0,57.0,1,0.0,Dermatology,Privado,Masculino
94593,134090.0,9.0,63.0,1,4.0,Neurologia/Neurocirugia,Medicare/Medicaid,Femenino

In [175]:
columna = 'Abogado Privado' 
valor_antiguo = 'Auto%#'       
valor_nuevo = '0'  
df2[columna] = df2[columna].replace(valor_antiguo, valor_nuevo)

In [176]:
columna = 'Especialidad' 
valor_antiguo = 'Auto%#'      
valor_nuevo = 'Cardiologia'  
df2[columna] = df2[columna].replace(valor_antiguo, valor_nuevo)

In [177]:
columna = 'Género' 
valor_antiguo = 'Auto%#'        
valor_nuevo = 'Masculino'  
df2[columna] = df2[columna].replace(valor_antiguo, valor_nuevo)

## Moda


Las ultimas 3 columnas de la base de datos sera rellenada con la moda ya que considero es lo mas conveniente.

In [178]:
moda_specialty = df2['Especialidad'].mode()[0]
df2['Especialidad'] = df2['Especialidad'].fillna(moda_specialty)

In [179]:
moda_insurance = df2['Seguro'].mode()[0]
df2['Seguro'] = df2['Seguro'].fillna(moda_insurance)

In [180]:
moda_gender = df2['Género'].mode()[0]
df2['Género'] = df2['Género'].fillna(moda_gender)

In [188]:
# 1. Mediana de la columna 'Importe'
mediana_importe = df2['Monto'].median()

# 2. Mediana de la columna 'Edad'
mediana_edad = df2['Edad'].median()

# 3. Imprimir los resultados
print(f"Mediana del Monto: {mediana_importe:.2f}")
print(f"Mediana de la Edad: {mediana_edad:.2f}")

Mediana del Monto: 94151.00
Mediana de la Edad: 43.00

In [190]:
# Columna de Importe
desviacion_importe = df2['Monto'].std()
min_importe = df2['Monto'].min()
max_importe = df2['Monto'].max()

# Columna de Edad
desviacion_edad = df2['Edad'].std()
min_edad = df2['Edad'].min()
max_edad = df2['Edad'].max()

print("--- Análisis de Dispersión y Rango ---")

## 1. Importe
print("\n Importe:")
print(f"   - Desviación Estándar (STD): {desviacion_importe:.2f}")
print(f"   - Valor Mínimo (Min): {min_importe:.2f}")
print(f"   - Valor Máximo (Max): {max_importe:.2f}")

## 2. Edad
print("\n Edad:")
print(f"   - Desviación Estándar (STD): {desviacion_edad:.2f}")
print(f"   - Valor Mínimo (Min): {min_edad:.2f}")
print(f"   - Valor Máximo (Max): {max_edad:.2f}")

--- Análisis de Dispersión y Rango ---

 Importe:
   - Desviación Estándar (STD): 191830.36
   - Valor Mínimo (Min): 1576.00
   - Valor Máximo (Max): 926411.00

 Edad:
   - Desviación Estándar (STD): 19.70
   - Valor Mínimo (Min): 0.00
   - Valor Máximo (Max): 87.00

In [192]:
df2['Género'].value_counts()

Género
Femenino     57095
Masculino    37499
Name: count, dtype: int64

In [194]:
df2['Especialidad'].value_counts()

Especialidad
Medicina Familiar            15810
Cirugia General              10708
Ginecologia y Obstetricia    10013
Anestesiologia                9883
Cirugia Ortopedica            8288
Medicina Interna              5934
Neurologia/Neurocirugia       5341
Medicina de Emergencia        5279
Cardiologia                   4881
Oftalmologia                  3744
Cirugia Urologica             2307
Residente                     2281
Radiologia                    2257
Pediatria                     1622
Dermatology                   1580
Cirujano Plastico             1535
Patologia                      825
Medicina Ocupacional           820
Cirugia Toracica               764
Medicina Fisica                722
Name: count, dtype: int64

In [195]:
df2['Seguro'].value_counts()

Seguro
Privado                         42673
Desconocido                     27747
Medicare/Medicaid               12685
Sin Seguro                       9194
Compensacion de Trabajadores     2295
Name: count, dtype: int64

In [181]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 94594 entries, 0 to 94593
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Monto            94594 non-null  float64
 1   Gravedad         94594 non-null  float64
 2   Edad             94594 non-null  float64
 3   Abogado Privado  94594 non-null  object
 4   Estado Civil     94594 non-null  float64
 5   Especialidad     94594 non-null  object
 6   Seguro           94594 non-null  object
 7   Género           94594 non-null  object
dtypes: float64(4), object(4)
memory usage: 5.8+ MB

In [182]:
df2.isnull().sum()

Monto              0
Gravedad           0
Edad               0
Abogado Privado    0
Estado Civil       0
Especialidad       0
Seguro             0
Género             0
dtype: int64

In [183]:
df2.to_csv("Base_limpia_Negligencia_Medica.csv", index=False)